### ISSUE TITLE
ClientScript stops working after updating to 10.8.5

### ISSUE THREAD

**Issue by LeviSnoot** [nicknsy/jellyscrub#46] opened 2022-09-25 13:53 UTC
I updated to Jellyfin 10.8.5 a few hours ago, and since then I have been unable to get scrubbing to return. I've manually injected `<script plugin="Jellyscrub" version="1.0.0.0" src="/Trickplay/ClientScript"></script>` to `index.html`, restarted JF and cleared browser cookies and cache for my server. When I play a video, everything behaves as if ClientScript isn't there. I can navigate to `https://server.com/Trickplay/ClientScript` and it shows up there. Not seeing any mention of Jellyscrub or ClientScript in my browsers inspector either, which I normally would.

EDIT: Looking at the source for `index.html`, I can conclude that the injected script does not appear there. This is odd given that I did clear cookies and cache and when I open the file in my jellyfin folder, the script is there. I have however seen similar behaviour before and maybe the solution is editing `main.jellyfin.bundle.js` instead of `index.html` since in my experience the changes do stick better from there. I unfortunately am not skilled enough at javascript yet to know where one could inject the script in that file however.

**Comment by LeviSnoot** [comment] 2022-09-25 20:25
For now I have remedied this using #42 as this seems like the most consistent way of doing it. Thanks @tam1m!

I'll keep this open in case someone not using nginx runs into the same issue.

**Comment by nicknsy** [comment] 2022-11-27 03:07
Unable to reproduce this issue when upgrading to 10.8.7 and on a new 10.8.7 install. Not sure if this was version specific or just a random occurrence but I'll close the issue in a couple of days unless you've experienced this further.

**Closed** 2022-12-30 01:49 UTC
